version: '3'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    volumes:
      - ./db:/var/lib/mysql
    env_file:
      - app/env.list
    networks:
      - fullcycle

  app:
    image: rbrayner/fullcycle-nodejs-mysql
    build:
      context: ./app
    container_name: app
    networks:
      - fullcycle
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - fullcycle
    ports: 
      - 8080:80
    depends_on:
      - app

networks:
  fullcycle:
    driver: bridge
